In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import shap

In [33]:
df = pd.read_csv('/content/heart.csv')

df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [34]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [35]:
x_train.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
237,60,1,0,140,293,0,0,170,0,1.2,1,2,3
106,69,1,3,160,234,1,0,131,0,0.1,1,1,2
10,54,1,0,140,239,0,1,160,0,1.2,2,0,2
153,66,0,2,146,278,0,0,152,0,0.0,1,1,2
77,59,1,1,140,221,0,1,164,1,0.0,2,0,2

In [36]:
y_train

237    0
106    1
10     1
153    1
77     1
      ..
75     1
22     1
72     1
15     1
168    0
Name: target, Length: 242, dtype: int64

In [37]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [38]:
log_classifier=LogisticRegression()
des_classifier=DecisionTreeClassifier()

In [39]:
log_classifier.fit(x_train,y_train)
des_classifier.fit(x_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [40]:
y_pred1=log_classifier.predict(x_test)
y_pred2=des_classifier.predict(x_test)

In [41]:
from sklearn.metrics import accuracy_score,confusion_matrix
print('Accuracy of logistic regression',accuracy_score(y_test,y_pred1))
print('Accuracy of Decision tree classifier',accuracy_score(y_test,y_pred2))

Accuracy of logistic regression 0.9016393442622951
Accuracy of Decision tree classifier 0.8360655737704918

In [42]:
print(confusion_matrix(y_test,y_pred1))

[[26  6]
 [ 0 29]]

In [49]:
from sklearn.metrics import precision_score,recall_score,f1_score
print('For Logistic Regression')
print('----------------------------------------------')
print('Precision:',precision_score(y_test,y_pred1))
print('Recall:',recall_score(y_test,y_pred1))
print('F1 score:',f1_score(y_test,y_pred1))

For Logistic Regression
----------------------------------------------
Precision: 0.8285714285714286
Recall: 1.0
F1 score: 0.90625

In [50]:
print('For Decision Tree')
print('----------------------------------------------')
print('Precision:',precision_score(y_test,y_pred2))
print('Recall',recall_score(y_test,y_pred2))
print('F1 score:',f1_score(y_test,y_pred2))

For Decision Tree
----------------------------------------------
Precision: 0.7714285714285715
Recall 0.9310344827586207
F1 score: 0.84375

In [51]:
#By default precision and recall is for positive
#let's try to get the both values for positive and negative using parameter average
print('For Logistic Regression')
print('Precision:',precision_score(y_test,y_pred1,average=None))
print('Recall:',recall_score(y_test,y_pred1,average=None))

For Logistic Regression
Precision: [1.         0.82857143]
Recall: [0.8125 1.    ]

In [52]:
#By default precision and recall is for positive
#let's try to get the both values for positive and negative using parameter average
print('For Decision Tree')
print('Precision:',precision_score(y_test,y_pred2,average=None))
print('Recall:',recall_score(y_test,y_pred2,average=None))

For Decision Tree
Precision: [0.92307692 0.77142857]
Recall: [0.75       0.93103448]

In [53]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       1.00      0.81      0.90        32
           1       0.83      1.00      0.91        29

    accuracy                           0.90        61
   macro avg       0.91      0.91      0.90        61
weighted avg       0.92      0.90      0.90        61